Major change: Upgraded Java compilation target version to Java 6.
This was required as the newer JDKs does not support Java 5 as target
anymore. And to be honest - it's time!
The error message on the build server system is
> Task :compileJava FAILED
error: Source option 5 is no longer supported. Use 6 or later.
error: Target option 1.5 is no longer supported. Use 1.6 or later.